#!/bin/sh

#
# from http://www.linuxquestions.org/questions/programming-9/find-grep-command-to-find-matching-files-print-filename-then-print-matching-content-328036/
#

find . -name "$1" -exec grep -i -n "$2" /dev/null {} \;
