#!/usr/bin/perl -w
#

my $pmr = shift @ARGV;
my $path = $pmr;
my $pmr_dir = "/local/PMR";

if ($pmr =~ /^[\d]+[\d,A-Z]+$/) {
  @pmr = split(/ */, $pmr);
  $first = $pmr[0];
  $second = $pmr[1];
  $path = "/ecurep/pmr/$first/$second/$path"
}

my $host = "ecurep.mainz.de.ibm.com";
#system("firefox https://$host/ae5/login/login.html#id=$pmr&path=$path&c=41864 &"

print "firefox https://$host/ae5/login/login.html#id=$pmr&path=$path &\n";
system("firefox https://$host/ae5/login/login.html#id=$pmr&path=$path &")
